interface TranscriptMessage {
  authorId: string;
  authorName: string;
  avatarURL?: string | null;
  content: string;
  attachments?: Array<{ url: string; name: string }>;
  timestamp: Date | string;
}

interface TranscriptOptions {
  guildName: string;
  ticketNumber: number;
  openedBy: string;
  claimedBy?: string | null;
  closedBy: string;
  subject?: string | null;
  createdAt: Date | string;
  closedAt: Date | string;
  messages: TranscriptMessage[];
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/\n/g, '<br>');
}

function formatTime(date: Date | string): string {
  const d = new Date(date);
  return d.toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    hour12: true,
  });
}

function isImageUrl(url: string): boolean {
  return /\.(png|jpe?g|gif|webp|svg)(\?.*)?$/i.test(url);
}

export function generateTranscriptHtml(opts: TranscriptOptions): string {
  const { guildName, ticketNumber, openedBy, claimedBy, closedBy, subject, createdAt, closedAt, messages } = opts;

  const nameMap = new Map<string, string>();
  for (const msg of messages) {
    nameMap.set(msg.authorId, msg.authorName);
  }

  function resolveMentions(text: string): string {
    return text.replace(/&lt;@!?(\d{17,20})&gt;/g, (_match, id) => {
      const name = nameMap.get(id);
      return name ? `<span class="mention">@${escapeHtml(name)}</span>` : `<span class="mention">@${id}</span>`;
    });
  }

  const messageHtml = messages
    .map((msg) => {
      const time = formatTime(msg.timestamp);
      const content = resolveMentions(escapeHtml(msg.content || ''));

      const attachmentHtml = (msg.attachments || [])
        .map((a) => {
          if (isImageUrl(a.url)) {
            return `<div class="att"><a href="${escapeHtml(a.url)}" target="_blank"><img src="${escapeHtml(a.url)}" alt="${escapeHtml(a.name)}"></a></div>`;
          }
          return `<div class="att"><a href="${escapeHtml(a.url)}" target="_blank">${escapeHtml(a.name)}</a></div>`;
        })
        .join('');

      return `<div class="msg"><span class="name">${escapeHtml(msg.authorName)}</span> <span class="time">${time}</span><div class="text">${content}${attachmentHtml}</div></div>`;
    })
    .join('\n');

  const claimedLine = claimedBy ? `<br>Claimed by: ${escapeHtml(claimedBy)}` : '';
  const subjectLine = subject ? `<br>Subject: ${escapeHtml(subject)}` : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Ticket #${ticketNumber} - ${escapeHtml(guildName)}</title>
<style>
  body { font-family: system-ui, sans-serif; font-size: 14px; color: #dcddde; background: #2b2d31; margin: 0; padding: 24px; line-height: 1.5; }
  .header { margin-bottom: 20px; padding-bottom: 12px; border-bottom: 1px solid #3f4147; }
  .header h1 { font-size: 18px; margin: 0 0 4px; color: #f2f3f5; }
  .header p { margin: 0; font-size: 13px; color: #949ba4; }
  .msg { padding: 6px 0; }
  .msg + .msg { border-top: 1px solid #3f4147; }
  .name { font-weight: 600; color: #f2f3f5; }
  .time { font-size: 11px; color: #949ba4; }
  .text { margin-top: 2px; word-wrap: break-word; }
  .mention { color: #c9cdfb; background: rgba(88,101,242,0.15); padding: 0 2px; border-radius: 3px; }
  .att { margin-top: 6px; }
  .att img { max-width: 400px; max-height: 300px; display: block; margin-top: 4px; border-radius: 4px; }
  .att a { color: #00a8fc; font-size: 13px; }
  .footer { margin-top: 20px; padding-top: 12px; border-top: 1px solid #3f4147; font-size: 11px; color: #949ba4; }
</style>
</head>
<body>
<div class="header">
  <h1>Ticket #${ticketNumber}</h1>
  <p>
    Server: ${escapeHtml(guildName)}<br>
    Opened by: ${escapeHtml(openedBy)} - Closed by: ${escapeHtml(closedBy)}${claimedLine}${subjectLine}<br>
    Opened: ${formatTime(createdAt)} - Closed: ${formatTime(closedAt)}<br>
    ${messages.length} message(s)
  </p>
</div>
${messageHtml || '<p style="color:#949ba4;">No messages recorded.</p>'}
<div class="footer">Transcript generated by Fluxy</div>
</body>
</html>`;
}
